### ISSUE TITLE
Add support for `*.overpassql` file extension

### ISSUE THREAD

**Issue by FloEdelmann** [Teiron/OverpassQL.tmLanguage#1]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to add add support for the `*.overpassql` file extension (the `*.overpass` extension can still be supported alongside) in this syntax highlighting definition and also rename/copy the existing `*.overpass` files to `*.overpassql`.

Some context:

* KDE's syntax highlighting engine has support for Overpass QL in `*.overpassql` files only: https://github.com/KDE/syntax-highlighting/blob/42a061b04c507de11b0fb240808fc65a7528d946/data/syntax/overpassql.xml
* GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by FloEdelmann** [comment]
@Teiron Would a pull request be accepted?

**Comment by Teiron** [comment]
Yes, feel free to make a PR :)

**Comment by FloEdelmann** [comment]
@Teiron I created a PR: #2.
